/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author TecRa Z50-C
 */
public class ActionButton extends javax.swing.JPanel {

    public void initEvent(int row) {
        panggilButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
            }
        });
    }
    
    /**
     * Creates new form PanelOpsi
     */
    public ActionButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panggilButton = new javax.swing.JButton();

        panggilButton.setBackground(new java.awt.Color(0, 102, 102));
        panggilButton.setForeground(new java.awt.Color(255, 255, 255));
        panggilButton.setText("Panggil");
        panggilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panggilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panggilButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(panggilButton)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panggilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panggilButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panggilButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton panggilButton;
    // End of variables declaration//GEN-END:variables
}
