/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author TecRa Z50-C
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    DefaultTableCellRenderer tableRenderer = new DefaultTableCellRenderer();
    Controller controller = new Controller();
    DefaultTableModel tabel;
    
    public Main() {
        
        initComponents();
        tableRenderer.setHorizontalAlignment(JLabel.CENTER);
        tabel = (DefaultTableModel) tabelAntrian.getModel();
        tabelAntrian.setDefaultRenderer(String.class, tableRenderer);
        tabelAntrian.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelAntrian.getColumnModel().getColumn(0).setMaxWidth(50);
        tabelAntrian.getColumnModel().getColumn(1).setPreferredWidth(50);
        tabelAntrian.getColumnModel().getColumn(1).setMaxWidth(50);
        tabelAntrian.getTableHeader().setBackground(Color.decode("#00717f"));
        tabelAntrian.getTableHeader().setForeground(Color.white);
        tabelAntrian.getTableHeader().setFont(new java.awt.Font("Poppins SemiBold", 0, 10));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        logoAplikasi = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        mainMenu = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tabelAntrian = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        panggilButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        filter = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        selesaiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 63, 65));
        setPreferredSize(new java.awt.Dimension(900, 600));

        navbar.setBackground(new java.awt.Color(0, 153, 153));
        navbar.setForeground(new java.awt.Color(100, 63, 65));
        navbar.setMinimumSize(new java.awt.Dimension(0, 0));
        navbar.setPreferredSize(new java.awt.Dimension(200, 440));
        navbar.setRequestFocusEnabled(false);

        logoAplikasi.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        logoAplikasi.setForeground(new java.awt.Color(255, 255, 255));
        logoAplikasi.setText("MyAntrian");

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Poppins Medium", 0, 10)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 0, 0));
        logoutButton.setText("Logout");
        logoutButton.setFocusPainted(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logoAplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(30, 30, 30))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoAplikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));
        mainMenu.setForeground(new java.awt.Color(255, 255, 255));

        judul.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(0, 0, 0));
        judul.setText("Layanan Antrian Pasien");

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setForeground(new java.awt.Color(255, 255, 255));

        tabelAntrian.setBackground(new java.awt.Color(255, 255, 255));
        tabelAntrian.setForeground(new java.awt.Color(0, 0, 0));
        tabelAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "No.", "Nama", "Waktu", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelAntrian.setFillsViewportHeight(true);
        tabelAntrian.setRowHeight(36);
        tabelAntrian.setShowGrid(false);
        tabelAntrian.setShowHorizontalLines(true);
        tabelAntrian.getTableHeader().setReorderingAllowed(false);
        tabelAntrian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelAntrianMouseReleased(evt);
            }
        });
        scrollPane.setViewportView(tabelAntrian);

        addButton.setBackground(new java.awt.Color(0, 102, 102));
        addButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Tambah Pasien");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        panggilButton.setBackground(new java.awt.Color(208, 198, 198));
        panggilButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        panggilButton.setForeground(new java.awt.Color(255, 255, 255));
        panggilButton.setText("Panggil Pasien");
        panggilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panggilButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(0, 102, 102));
        resetButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset Antrian");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        filter.setBackground(new java.awt.Color(0, 102, 102));
        filter.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        filter.setForeground(new java.awt.Color(255, 255, 255));
        filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Dalam Antrian", "Sedang Periksa", "Sudah Selesai" }));
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 102, 102));
        saveButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save ke TXT");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        nextButton.setBackground(new java.awt.Color(0, 102, 102));
        nextButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("Panggil Selanjutnya");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        selesaiButton.setBackground(new java.awt.Color(208, 198, 198));
        selesaiButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        selesaiButton.setForeground(new java.awt.Color(255, 255, 255));
        selesaiButton.setText("Selesai Periksa");
        selesaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPane)
                    .addGroup(mainMenuLayout.createSequentialGroup()
                        .addComponent(filter, 0, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selesaiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panggilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(judul)
                .addGap(30, 30, 30)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton)
                    .addComponent(panggilButton)
                    .addComponent(selesaiButton)
                    .addComponent(nextButton)
                    .addComponent(addButton)
                    .addComponent(resetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:

        String nama = "";
        nama = JOptionPane.showInputDialog(this, "Masukkan Nama Pasien");
        while (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon Masukkan Nama!");
            nama = JOptionPane.showInputDialog(this, "Masukkan Nama Pasien");
        }
        
        controller.addPasien(nama);
        tabel.addRow(new Object[] {false,
            controller.getPasien(controller.getNomor()).getNomor(),
            controller.getPasien(controller.getNomor()).getNama(),    
            controller.getPasien(controller.getNomor()).getWaktu(),
            controller.getPasien(controller.getNomor()).getStatus()
        });
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void tabelAntrianMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAntrianMouseReleased
        // TODO add your handling code here:
        boolean panggilButton = false;
        boolean selesaiButton = false;
        
        for(int i = 0; i < tabelAntrian.getRowCount(); i++) {
            if((boolean) tabelAntrian.getValueAt(i, 0) && tabelAntrian.getValueAt(i, 4).toString().equals("Dalam Antrian")) {
                panggilButton = true;
            } else if ((boolean) tabelAntrian.getValueAt(i, 0) && tabelAntrian.getValueAt(i, 4).toString().equals("Sedang Periksa")) {
                selesaiButton = true;
            }
        }
        
        this.panggilButton.setBackground(panggilButton ? Color.decode("#006666") : Color.decode("#D0C6C6"));
        this.selesaiButton.setBackground(selesaiButton ? Color.decode("#006666") : Color.decode("#D0C6C6"));
        
    }//GEN-LAST:event_tabelAntrianMouseReleased

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        controller.saveTXT(filter.getSelectedItem().toString());
    }//GEN-LAST:event_saveButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < tabelAntrian.getRowCount(); i++) {
            if(tabelAntrian.getValueAt(i, 4).toString().equals("Dalam Antrian")) {
                controller.getPasien((int)tabel.getValueAt(i, 1) - 1).setStatus("Sedang Periksa");
                tabel.insertRow(i, new Object[] {false,
                controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getNomor(),
                controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getNama(),    
                controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getWaktu(),
                controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getStatus()
                });
                tabel.removeRow(i + 1);
                panggilButton.setBackground(Color.decode("#D0C6C6"));
                break;
            }
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        tabel.setRowCount(0);
        controller.flushPasien();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void panggilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panggilButtonActionPerformed
        // TODO add your handling code here:
        if (panggilButton.getBackground().getRGB() == -16751002) {
            for(int i = 0; i < tabelAntrian.getRowCount(); i++) {
                if((boolean) tabelAntrian.getValueAt(i, 0) && tabelAntrian.getValueAt(i, 4).toString().equals("Dalam Antrian")) {
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).setStatus("Sedang Periksa");
                    tabel.insertRow(i, new Object[] {false,
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getNomor(),
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getNama(),    
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getWaktu(),
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getStatus()
                    });
                    tabel.removeRow(i + 1);
                }
            }
        }
        panggilButton.setBackground(Color.decode("#D0C6C6"));
    }//GEN-LAST:event_panggilButtonActionPerformed

    private void selesaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiButtonActionPerformed
        // TODO add your handling code here:
                if (selesaiButton.getBackground().getRGB() == -16751002) {
            for(int i = 0; i < tabelAntrian.getRowCount(); i++) {
                if((boolean) tabelAntrian.getValueAt(i, 0) && tabelAntrian.getValueAt(i, 4).toString().equals("Sedang Periksa")) {
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).setStatus("Sudah Selesai");
                    tabel.insertRow(i, new Object[] {false,
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getNomor(),
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getNama(),    
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getWaktu(),
                    controller.getPasien((int)tabel.getValueAt(i, 1) - 1).getStatus()
                    });
                    tabel.removeRow(i + 1);
                }
            }
        }
        selesaiButton.setBackground(Color.decode("#D0C6C6"));
    }//GEN-LAST:event_selesaiButtonActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:
        tabel.setRowCount(0);
        for (int i = 0; i < controller.getJumlahPasien(); i++) {
            if(controller.getPasien(i).getStatus().equals(filter.getSelectedItem().toString()) || 
               filter.getSelectedItem().toString().equals("Semua") ) {
                tabel.addRow(new Object[] {false,
                            controller.getPasien(i).getNomor(),
                            controller.getPasien(i).getNama(),    
                            controller.getPasien(i).getWaktu(),
                            controller.getPasien(i).getStatus()});
            }
        }
    }//GEN-LAST:event_filterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> filter;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel logoAplikasi;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel navbar;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton panggilButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton selesaiButton;
    private javax.swing.JTable tabelAntrian;
    // End of variables declaration//GEN-END:variables
}