/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author TecRa Z50-C
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    Controller controller = new Controller();
    DefaultTableModel tabel;
    
    public Main() {
        
        initComponents();
        tabel = (DefaultTableModel) tabelAntrian.getModel();
        callPasien.setVisible(false);
        tabelAntrian.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelAntrian.getColumnModel().getColumn(0).setMaxWidth(50);
        tabelAntrian.getColumnModel().getColumn(1).setPreferredWidth(50);
        tabelAntrian.getColumnModel().getColumn(1).setMaxWidth(50);
        tabelAntrian.getTableHeader().setBackground(Color.decode("#00717f"));
        tabelAntrian.getTableHeader().setForeground(Color.white);
        tabelAntrian.getTableHeader().setFont(new java.awt.Font("Poppins SemiBold", 0, 10));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        logoAplikasi = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        mainMenu = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tabelAntrian = new javax.swing.JTable();
        addPasien = new javax.swing.JButton();
        callPasien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 63, 65));

        sidebar.setBackground(new java.awt.Color(0, 153, 153));
        sidebar.setForeground(new java.awt.Color(100, 63, 65));
        sidebar.setMinimumSize(new java.awt.Dimension(0, 0));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 440));
        sidebar.setRequestFocusEnabled(false);

        logoAplikasi.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        logoAplikasi.setForeground(new java.awt.Color(255, 255, 255));
        logoAplikasi.setText("MyAntrian");

        logOut.setBackground(new java.awt.Color(255, 255, 255));
        logOut.setFont(new java.awt.Font("Poppins Medium", 0, 10)); // NOI18N
        logOut.setForeground(new java.awt.Color(0, 0, 0));
        logOut.setText("Logout");
        logOut.setFocusPainted(false);
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logoAplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOut)
                .addGap(30, 30, 30))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoAplikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));
        mainMenu.setForeground(new java.awt.Color(255, 255, 255));

        heading.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(0, 0, 0));
        heading.setText("Layanan Antrian Pasien");

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setForeground(new java.awt.Color(255, 255, 255));

        tabelAntrian.setBackground(new java.awt.Color(255, 255, 255));
        tabelAntrian.setForeground(new java.awt.Color(0, 0, 0));
        tabelAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "No.", "Nama", "Waktu", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelAntrian.setFillsViewportHeight(true);
        tabelAntrian.setRowHeight(36);
        tabelAntrian.setShowGrid(false);
        tabelAntrian.setShowHorizontalLines(true);
        tabelAntrian.getTableHeader().setReorderingAllowed(false);
        tabelAntrian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAntrianMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(tabelAntrian);

        addPasien.setBackground(new java.awt.Color(0, 102, 102));
        addPasien.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        addPasien.setForeground(new java.awt.Color(255, 255, 255));
        addPasien.setText("Tambah Pasien");
        addPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasienActionPerformed(evt);
            }
        });

        callPasien.setBackground(new java.awt.Color(0, 102, 102));
        callPasien.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        callPasien.setForeground(new java.awt.Color(255, 255, 255));
        callPasien.setText("Panggil Pasien");

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heading)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(callPasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPasien))
                    .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(heading)
                .addGap(18, 18, 18)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPasien)
                    .addComponent(callPasien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
            .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_logOutActionPerformed

    private void addPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasienActionPerformed
        // TODO add your handling code here:

        String nama = "";
        nama = JOptionPane.showInputDialog(this, "Masukkan Nama Pasien");
        while (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon Masukkan Nama!");
            nama = JOptionPane.showInputDialog(this, "Masukkan Nama Pasien");
        }
        
        controller.addPasien(nama);
        tabel.addRow(new Object[] {false,
            controller.getPasien(controller.getNomor()).getNomor(),
            controller.getPasien(controller.getNomor()).getNama(),    
            controller.getPasien(controller.getNomor()).getWaktu(),
            controller.getPasien(controller.getNomor()).getStatus(),
        });
        
    }//GEN-LAST:event_addPasienActionPerformed

    private void tabelAntrianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAntrianMouseClicked
        // TODO add your handling code here:
        for(int i = 0; i < tabelAntrian.getRowCount(); i++) {
            if((boolean) tabelAntrian.getValueAt(i, 0)) {
                callPasien.setVisible(true);
                break;
            } else {
                callPasien.setVisible(false);
            }    
        }
            
    }//GEN-LAST:event_tabelAntrianMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPasien;
    private javax.swing.JButton callPasien;
    private javax.swing.JLabel heading;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel logoAplikasi;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable tabelAntrian;
    // End of variables declaration//GEN-END:variables
}