/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TecRa Z50-C
 */
public class MainMenu extends javax.swing.JFrame {

    Controller controller = new Controller();
    protected DefaultTableModel tabel;
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        
        initComponents();
        this.tabel = (DefaultTableModel) tabelAntrian.getModel();
        tabelAntrian.getColumnModel().getColumn(4).setCellRenderer(new ActionButtonRenderer());
        tabelAntrian.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabelAntrian.getColumnModel().getColumn(4).setMaxWidth(100);
        tabelAntrian.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelAntrian.getColumnModel().getColumn(0).setMaxWidth(50);
        tabelAntrian.getTableHeader().setFont(new java.awt.Font("Poppins SemiBold", 0, 10));
        tabelAntrian.getTableHeader().setBackground(Color.decode("#00717f"));
        tabelAntrian.getTableHeader().setForeground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        namaApp = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JPanel();
        headingMenu = new javax.swing.JLabel();
        buttonTambahPasien = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        tabelAntrian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 63, 65));
        setPreferredSize(new java.awt.Dimension(740, 460));

        navbar.setBackground(new java.awt.Color(0, 153, 153));
        navbar.setForeground(new java.awt.Color(100, 63, 65));
        navbar.setMinimumSize(new java.awt.Dimension(0, 0));
        navbar.setPreferredSize(new java.awt.Dimension(200, 440));
        navbar.setRequestFocusEnabled(false);

        namaApp.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        namaApp.setForeground(new java.awt.Color(255, 255, 255));
        namaApp.setText("MyAntrian");

        logOut.setBackground(new java.awt.Color(255, 255, 255));
        logOut.setFont(new java.awt.Font("Poppins Medium", 0, 10)); // NOI18N
        logOut.setForeground(new java.awt.Color(0, 0, 0));
        logOut.setText("Log out");
        logOut.setFocusPainted(false);
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(namaApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOut)
                .addGap(25, 25, 25))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaApp)
                    .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));
        mainMenu.setForeground(new java.awt.Color(255, 255, 255));

        headingMenu.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        headingMenu.setForeground(new java.awt.Color(0, 0, 0));
        headingMenu.setText("Layanan Antrian Rumah Sakit");

        buttonTambahPasien.setBackground(new java.awt.Color(0, 153, 153));
        buttonTambahPasien.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        buttonTambahPasien.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambahPasien.setText("Tambah Pasien");
        buttonTambahPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahPasienActionPerformed(evt);
            }
        });

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setForeground(new java.awt.Color(255, 255, 255));

        tabelAntrian.setBackground(new java.awt.Color(255, 255, 255));
        tabelAntrian.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        tabelAntrian.setForeground(new java.awt.Color(0, 0, 0));
        tabelAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nama", "Waktu", "Status", "Opsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelAntrian.setFillsViewportHeight(true);
        tabelAntrian.setRowHeight(35);
        tabelAntrian.setShowGrid(false);
        tabelAntrian.setShowHorizontalLines(true);
        scrollPane.setViewportView(tabelAntrian);

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headingMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTambahPasien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(headingMenu)
                .addGap(18, 18, 18)
                .addComponent(buttonTambahPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_logOutActionPerformed

    private void buttonTambahPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahPasienActionPerformed
        // TODO add your handling code here:
        String nama = "";
        nama = JOptionPane.showInputDialog(this, "Masukkan Nama Pasien");
        while(nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap Masukkan Nama!");
            nama = JOptionPane.showInputDialog(this, "Masukkan Nama Pasien");
        }
        controller.addPasien(nama);
        
        tabel.addRow(new Object[] {controller.getAntrian(controller.getNomor() - 1).getNomor(),
                                   controller.getAntrian(controller.getNomor() - 1).getNama(),
                                   controller.getAntrian(controller.getNomor() - 1).getWaktu(),
                                   controller.getAntrian(controller.getNomor() - 1).getStatus(),
                                   controller.getAntrian(controller.getNomor() - 1).getPanggilPasien()});
    }//GEN-LAST:event_buttonTambahPasienActionPerformed

    protected JTable getTabelAntrian() {
        return tabelAntrian;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTambahPasien;
    private javax.swing.JLabel headingMenu;
    private javax.swing.JButton logOut;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaApp;
    private javax.swing.JPanel navbar;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabelAntrian;
    // End of variables declaration//GEN-END:variables
    
}
